# Zadanie domowe -- interpolacja dwusześcienna

Interpolacja dwusześcienna, to podobnie jak w przypadku interpolacji dwuliniowej, rozszerzenie idei interpolacji jednowymiarowej na dwuwymiarową siatkę.
W trakcie jej obliczania wykorzystywane jest 16 pikseli z otoczenia (dla dwuliniowej 4).
Skutkuje to zwykle lepszymi wynikami - obraz wyjściowy jest bardziej gładki i z mniejszą liczbą artefaktów.
Ceną jest znaczny wzrost złożoności obliczeniowej (zostało to zaobserwowane podczas ćwiczenia).

Interpolacja dana jest wzorem:
\begin{equation}
I(i,j) = \sum_{i=0}^{3} \sum_{j=0}^{3} a_{ij} x^i y^j
\end{equation}

Zadanie sprowadza się zatem do wyznaczenia 16 współczynników $a_{ij}$.
W tym celu wykorzystuje się, oprócz wartość w puntach $A$ (0,0), $B$ (1 0), $C$ (1,1), $D$ (0,1) (por. rysunek dotyczący interpolacji dwuliniowej), także pochodne cząstkowe $A_x$, $A_y$, $A_{xy}$.
Pozwala to rozwiązać układ 16-tu równań.

Jeśli zgrupujemy parametry $a_{ij}$:
\begin{equation}
a = [ a_{00}~a_{10}~a_{20}~a_{30}~a_{01}~a_{11}~a_{21}~a_{31}~a_{02}~a_{12}~a_{22}~a_{32}~a_{03}~a_{13}~a_{23}~a_{33}]
\end{equation}

i przyjmiemy:
\begin{equation}
x = [A~B~D~C~A_x~B_x~D_x~C_x~A_y~B_y~D_y~C_y~A_{xy}~B_{xy}~D_{xy}~C_{xy}]^T
\end{equation}

To zagadnienie można opisać w postaci równania liniowego:
\begin{equation}
Aa = x
\end{equation}
gdzie macierz $A^{-1}$ dana jest wzorem:

\begin{equation}
A^{-1} =
\begin{bmatrix}
1& 0& 0& 0& 0& 0& 0& 0& 0& 0& 0& 0& 0& 0& 0& 0 \\
0&  0&  0&  0&  1&  0&  0&  0&  0&  0&  0&  0&  0&  0&  0&  0 \\
-3&  3&  0&  0& -2& -1&  0&  0&  0&  0&  0&  0&  0&  0&  0&  0 \\
2& -2&  0&  0&  1&  1&  0&  0&  0&  0&  0&  0&  0&  0&  0&  0 \\
0&  0&  0&  0&  0&  0&  0&  0&  1&  0&  0&  0&  0&  0&  0&  0 \\
0&  0&  0&  0&  0&  0&  0&  0&  0&  0&  0&  0&  1&  0&  0&  0 \\
0&  0&  0&  0&  0&  0&  0&  0& -3&  3&  0&  0& -2& -1&  0&  0 \\
0&  0&  0&  0&  0&  0&  0&  0&  2& -2&  0&  0&  1&  1&  0&  0 \\
-3&  0&  3&  0&  0&  0&  0&  0& -2&  0& -1&  0&  0&  0&  0&  0 \\
0&  0&  0&  0& -3&  0&  3&  0&  0&  0&  0&  0& -2&  0& -1&  0 \\
9& -9& -9&  9&  6&  3& -6& -3&  6& -6&  3& -3&  4&  2&  2&  1 \\
-6&  6&  6& -6& -3& -3&  3&  3& -4&  4& -2&  2& -2& -2& -1& -1 \\
2&  0& -2&  0&  0&  0&  0&  0&  1&  0&  1&  0&  0&  0&  0&  0 \\
0&  0&  0&  0&  2&  0& -2&  0&  0&  0&  0&  0&  1&  0&  1&  0 \\
-6&  6&  6& -6& -4& -2&  4&  2& -3&  3& -3&  3& -2& -1& -2& -1 \\
4& -4& -4&  4&  2&  2& -2& -2&  2& -2&  2& -2&  1&  1&  1&  1 \\
\end{bmatrix}
\end{equation}

Potrzebne w rozważaniach pochodne cząstkowe obliczane są wg. następującego przybliżenia (przykład dla punktu A):
\begin{equation}
A_x = \frac{I(i+1,j) - I(i-1,j)}{2}
\end{equation}
\begin{equation}
A_y = \frac{I(i,j+1) - I(i,j-1)}{2}
\end{equation}
\begin{equation}
A_{xy} = \frac{I(i+1,j+1) - I(i-1,j) - I(i,j-1) + I(i,j)}{4}
\end{equation}

## Zadanie

Wykorzystując podane informacje zaimplementuj interpolację dwusześcienną.
Uwagi:
- macierz $A^{-1}$ dostępna jest w pliku *a_invert.py*
- trzeba się zastanowić nad potencjalnym wykraczaniem poza zakres obrazka (jak zwykle).

Ponadto dokonaj porównania liczby operacji arytmetycznych i dostępów do pamięci koniecznych przy realizacji obu metod interpolacji: dwuliniowej i dwusześciennej.

In [13]:
import cv2
import os
import requests
from matplotlib import pyplot as plt
import numpy as np
from math import floor

url = 'https://raw.githubusercontent.com/vision-agh/poc_sw/master/05_Resolution/'

fileName = "ainvert.py"
if not os.path.exists(fileName):
    r = requests.get(url + fileName, allow_redirects=True)
    open(fileName, 'wb').write(r.content)

#TODO Do samodzielnej implementacji

import ainvert
ainvert.A_invert


# TODO: Do samodzielnej implemetantacji
def better_scaler(image,scale_x=1.5,scale_y=1.5):
    size_y, size_x = image.shape
    new_size_x = int(size_x*scale_x)
    new_size_y = int(size_y*scale_y)

    new_image = np.zeros((new_size_y,new_size_x))
    for y in range(new_image.shape[0]):
        for x in range(new_image.shape[1]):
            pos_x = x/scale_x
            pos_y = y/scale_y
            i1,j1 = min(floor(x/scale_x),size_x-2),min(floor(y/scale_y),size_y-2)
            i2,j2=i1+1,j1+1
            
            rounded_pos_x = min(round(pos_x), (size_x-1))
            rounded_pos_y = min(round(pos_y), (size_y-1))
            
            fA,fB,fC,fD = image[j1,i1],image[j1,i2],image[j2,i2],image[j2,i1]
            
            Ax = (image[j1,i1+1]-image[j1,i1-1])/2
            Ay = (image[j1+1,i1]-image[j1-1,i1])/2
            Axy = (image[j1+1,i1+1]-image[j1,i1-1]-image[j1-1,i1]-image[j1,i1])/4
            
            Bx = (image[j1,i1+1]-image[j1,i1-1])/2
            By = (image[j1+1,i1]-image[j1-1,i1])/2
            Bxy = (image[j1+1,i1+1]-image[j1,i1-1]-image[j1-1,i1]-image[j1,i1])/4
            
            Cx = (image[j1,i1+1]-image[j1,i1-1])/2
            Cy = (image[j1+1,i1]-image[j1-1,i1])/2
            Cxy = (image[j1+1,i1+1]-image[j1,i1-1]-image[j1-1,i1]-image[j1,i1])/4
            
            Dx = (image[j1,i1+1]-image[j1,i1-1])/2
            Dy = (image[j1+1,i1]-image[j1-1,i1])/2
            Dxy = (image[j1+1,i1+1]-image[j1,i1-1]-image[j1-1,i1]-image[j1,i1])/4
            
            
            x_vectorr = [fA,fB,fC,fD, Ax, Bx, Cx, Dx, Ay, By, Cy, Dy, Axy, Bxy, Cxy, Dxy]
            a = np.matmul(ainvert.A_invert, x_vectorr)
            print(a.reshape((4,4)))
#             print(a)
#             image[]
#             for n in range(3):
            
            
image = cv2.imread(f'parrot.bmp',cv2.IMREAD_GRAYSCALE)
better_scaler(image)

C:\Users\ogsimp\AppData\Local\Temp\ipykernel_20964\4103578778.py:41: RuntimeWarning: overflow encountered in ubyte_scalars
  Ay = (image[j1+1,i1]-image[j1-1,i1])/2
C:\Users\ogsimp\AppData\Local\Temp\ipykernel_20964\4103578778.py:42: RuntimeWarning: overflow encountered in ubyte_scalars
  Axy = (image[j1+1,i1+1]-image[j1,i1-1]-image[j1-1,i1]-image[j1,i1])/4
C:\Users\ogsimp\AppData\Local\Temp\ipykernel_20964\4103578778.py:45: RuntimeWarning: overflow encountered in ubyte_scalars
  By = (image[j1+1,i1]-image[j1-1,i1])/2
C:\Users\ogsimp\AppData\Local\Temp\ipykernel_20964\4103578778.py:46: RuntimeWarning: overflow encountered in ubyte_scalars
  Bxy = (image[j1+1,i1+1]-image[j1,i1-1]-image[j1-1,i1]-image[j1,i1])/4
C:\Users\ogsimp\AppData\Local\Temp\ipykernel_20964\4103578778.py:49: RuntimeWarning: overflow encountered in ubyte_scalars
  Cy = (image[j1+1,i1]-image[j1-1,i1])/2
C:\Users\ogsimp\AppData\Local\Temp\ipykernel_20964\4103578778.py:50: RuntimeWarning: overflow encountered in ubyte_sca

[[ 145.     2.    -9.     6. ]
 [ 121.    52.5 -157.5  105. ]
 [-369.  -157.5  508.5 -339. ]
 [ 246.   105.  -339.   226. ]]
[[ 145.     2.    -9.     6. ]
 [ 121.    52.5 -157.5  105. ]
 [-369.  -157.5  508.5 -339. ]
 [ 246.   105.  -339.   226. ]]
[[ 144.     0.     3.    -2. ]
 [ 120.5   52.  -156.   104. ]
 [-364.5 -156.   459.  -306. ]
 [ 243.   104.  -306.   204. ]]
[[ 145.     1.5    1.5   -1. ]
 [ 120.5   52.5 -157.5  105. ]
 [-361.5 -157.5  436.5 -291. ]
 [ 241.   105.  -291.   194. ]]
[[ 145.     1.5    1.5   -1. ]
 [ 120.5   52.5 -157.5  105. ]
 [-361.5 -157.5  436.5 -291. ]
 [ 241.   105.  -291.   194. ]]
[[ 147.     1.5   -1.5    1. ]
 [ 120.5   51.5 -154.5  103. ]
 [-364.5 -154.5  445.5 -297. ]
 [ 243.   103.  -297.   198. ]]
[[ 148.     2.     3.    -2. ]
 [ 120.    51.5 -154.5  103. ]
 [-351.  -154.5  391.5 -261. ]
 [ 234.   103.  -261.   174. ]]
[[ 148.     2.     3.    -2. ]
 [ 120.    51.5 -154.5  103. ]
 [-351.  -154.5  391.5 -261. ]
 [ 234.   103.  -261.   174. ]]


[[ 132.     1.     0.     0. ]
 [ 125.5   61.5 -184.5  123. ]
 [-373.5 -184.5  526.5 -351. ]
 [ 249.   123.  -351.   234. ]]
[[ 133.    2.    3.   -2.]
 [ 127.   62. -186.  124.]
 [-372. -186.  504. -336.]
 [ 248.  124. -336.  224.]]
[[ 133.    2.    3.   -2.]
 [ 127.   62. -186.  124.]
 [-372. -186.  504. -336.]
 [ 248.  124. -336.  224.]]
[[ 136.      3.5     1.5    -1.  ]
 [   0.     61.25 -183.75  122.5 ]
 [   6.   -183.75  497.25 -331.5 ]
 [  -4.    122.5  -331.5   221.  ]]
[[ 140.      4.      0.      0.  ]
 [ 127.     59.25 -177.75  118.5 ]
 [-378.   -177.75  470.25 -313.5 ]
 [ 252.    118.5  -313.5   209.  ]]
[[ 140.      4.      0.      0.  ]
 [ 127.     59.25 -177.75  118.5 ]
 [-378.   -177.75  470.25 -313.5 ]
 [ 252.    118.5  -313.5   209.  ]]
[[ 144.      2.     -6.      4.  ]
 [ 126.     54.25 -162.75  108.5 ]
 [-408.   -162.75  551.25 -367.5 ]
 [ 272.    108.5  -367.5   245.  ]]
[[ 144.    127.5  -385.5   257.  ]
 [ 123.5    50.25 -150.75  100.5 ]
 [-442.5  -150.75  587.

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

